trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  PW_Headless: 'true'
  PW_BaseUrl: 'https://opensource-demo.orangehrmlive.com/'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 10.0.x
  - script: dotnet restore
    displayName: Restore
  - script: dotnet build --no-restore
    displayName: Build
  - script: pwsh bin/Debug/net10.0/playwright.ps1 install --with-deps chromium
    displayName: Install Playwright Chromium
  - script: dotnet test --no-restore --settings .runsettings --logger "trx;LogFileName=results.trx"
    displayName: Run tests
    env:
      PW_Username: $(PW_USERNAME)
      PW_Password: $(PW_PASSWORD)
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: TestResults
  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: TestResults
      artifact: playwright-test-results
